[cnbeta_front]
title = "cnbeta 首页"
url = "https://m.cnbeta.com.tw/wap"
entrySelector = "#info_list > .list"
titleSelector = "a"
linkSelector = "a"

[wikivoyage]
title = "Wikivoyage recommendations"
url = "https://en.wikivoyage.org/wiki/Main_Page"
entrySelector = ".jcarousel-wrapper .jcarousel-item"
titleSelector = "h2"
linkSelector = "h2 a"
