[default]
timeout = 300
#waitUntil = "load"
waitUntil = "networkidle"

[cq-gongkaoleida-zkgg]
title = "重庆市公考雷达"
url = "https://www.gongkaoleida.com/area/2460-2461-0-2,3,59,78-124"
entrySelector = "body > section > div.mdn-content-box.clearfix > div > div"
titleSelector = ".notice-list > ul:nth-child > li:nth-child > h5:nth-child > a:nth-child"
linkSelector = ".notice-list > ul:nth-child > li:nth-child > h5:nth-child > a:nth-child"
contentSelector = ".article-detail"
dateSelector = ".date"
dateFormat = "yyyy-MM-dd hh:mm:ss"

[cq-rlsbj-zkgg]
title = "重庆市人社局-事业单位公开招聘"
url = "https://rlsbj.cq.gov.cn/zwxx_182/sydw/"
entrySelector = "body > div.page-list.clearfix > ul:nth-child"
titleSelector = "ul.tab-item:nth-child > li:nth-child > a:nth-child"
linkSelector = "ul.tab-item:nth-child > li:nth-child > a:nth-child"
contentSelector = ".zwxl-article"
dateSelector = "ul.tab-item:nth-child > li:nth-child > span:nth-child"
dateFormat = "yyyy-MM-dd"
