[default]
timeout = 300
#waitUntil = "load"
waitUntil = "networkidle"

[cq-gongkaoleida-zkgg]
title = "重庆市公考雷达"
url = "https://www.gongkaoleida.com/area/2460-2461-0-2,3,59,78-124"
entrySelector = "body > section > div.mdn-content-box.clearfix > div > div"
titleSelector = ".notice-list > ul:nth-child(1) > li:nth-child(1) > h5:nth-child(1) > a:nth-child(3)"
linkSelector = ".notice-list > ul:nth-child(1) > li:nth-child(1) > h5:nth-child(1) > a:nth-child(3)"
contentSelector = ".article-detail"
dateSelector = ".date"
dateFormat = "yyyy-MM-dd hh:mm:ss"

[cq-rlsbj-zkgg]
title = "重庆市人社局-事业单位公开招聘"
url = "https://rlsbj.cq.gov.cn/zwxx_182/sydw/"
entrySelector = "body > div.page-list.clearfix > ul:nth-child(3)"
titleSelector = "ul.tab-item:nth-child(3) > li:nth-child(1) > a:nth-child(1)"
linkSelector = "ul.tab-item:nth-child(3) > li:nth-child(1) > a:nth-child(1)"
contentSelector = ".zwxl-article"
dateSelector = "ul.tab-item:nth-child(3) > li:nth-child(1) > span:nth-child(2)"
dateFormat = "yyyy-MM-dd"

[52pojie-today]
title = "吾爱破解 今日热帖"
url = "https://www.52pojie.cn/misc.php?mod=ranklist&type=thread&view=replies&orderby=today"
entrySelector = "td.icn + th"
titleSelector = "a"
linkSelector = "a"
